{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-15-d644e0579c4e>, line 11)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-15-d644e0579c4e>\"\u001b[1;36m, line \u001b[1;32m11\u001b[0m\n\u001b[1;33m    cur.copy_expert(\"copy {} from STDIN CSV HEADER QUOTE ',\"'\".format('PBSALES_US'), f)\u001b[0m\n\u001b[1;37m                                                                       ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "import psycopg2\n",
    "\n",
    "conn = psycopg2.connect(dbname='postgres', host='localhost', port=5432,user='postgres', password='ranjeet')\n",
    "print(\"Connecting to Database\")\n",
    "cur = conn.cursor()\n",
    "f = open('C:\\\\Users\\\\meran\\\\Downloads\\\\PS.csv', \"r\")\n",
    "        # Truncate the table first\n",
    "cur.execute(\"Truncate {} Cascade;\".format('PBSALES_US'))\n",
    "print(\"Truncated {}\".format('PBSALES_US'))\n",
    "        # Load table from the file with header\n",
    "cur.copy_expert(\"copy {} from STDIN CSV HEADER QUOTE '\\\"'\".format('PBSALES_US'), f)\n",
    "cur.execute(\"commit;\")\n",
    "print(\"Loaded data into {}\".format('PBSALES_US'))\n",
    "conn.close()\n",
    "print(\"DB connection closed.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pandas\n",
      "  Downloading pandas-1.0.1-cp38-cp38-win_amd64.whl (9.2 MB)\n",
      "Requirement already satisfied: python-dateutil>=2.6.1 in c:\\users\\meran\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\\localcache\\local-packages\\python38\\site-packages (from pandas) (2.8.1)\n",
      "Collecting numpy>=1.13.3\n",
      "  Downloading numpy-1.18.1-cp38-cp38-win_amd64.whl (12.8 MB)\n",
      "Collecting pytz>=2017.2\n",
      "  Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\meran\\appdata\\local\\packages\\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\\localcache\\local-packages\\python38\\site-packages (from python-dateutil>=2.6.1->pandas) (1.14.0)\n",
      "Installing collected packages: numpy, pytz, pandas\n",
      "Successfully installed numpy-1.18.1 pandas-1.0.1 pytz-2019.3\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  WARNING: The script f2py.exe is installed in 'C:\\Users\\meran\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\Scripts' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n"
     ]
    }
   ],
   "source": [
    "pip install pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "to_sql() got an unexpected keyword argument 'null'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-36-0253f6370251>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mengine\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcreate_engine\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'postgresql://postgres:ranjeet@localhost:5432/postgres'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 8\u001b[1;33m \u001b[0mdf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mto_sql\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'pbsales_us'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mengine\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mif_exists\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'append'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mindex\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mnull\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m: to_sql() got an unexpected keyword argument 'null'"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "import pandas as pd\n",
    "df = pd.read_csv('C:\\\\Users\\\\meran\\\\Downloads\\\\PS.csv')\n",
    "df.columns = [c.lower() for c in df.columns] #postgres doesn't like capitals or spaces\n",
    "\n",
    "from sqlalchemy import create_engine\n",
    "engine = create_engine('postgresql://postgres:ranjeet@localhost:5432/postgres')\n",
    "\n",
    "df.to_sql('pbsales_us', engine, if_exists='append',index=False,null=\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "to_csv() got an unexpected keyword argument 'null'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-35-3872addfe94f>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     11\u001b[0m \u001b[0mcur\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mconn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcursor\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     12\u001b[0m \u001b[0moutput\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mio\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mStringIO\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 13\u001b[1;33m \u001b[0mdf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mto_csv\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0moutput\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msep\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'\\n'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mheader\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mindex\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mnull\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     14\u001b[0m \u001b[0moutput\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mseek\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     15\u001b[0m \u001b[0mcontents\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0moutput\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mgetvalue\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: to_csv() got an unexpected keyword argument 'null'"
     ]
    }
   ],
   "source": [
    "from sqlalchemy import create_engine\n",
    "import psycopg2 \n",
    "import io\n",
    "\n",
    "\n",
    "engine = create_engine('postgresql://postgres:ranjeet@localhost:5432/postgres')\n",
    "\n",
    "df.head(0).to_sql('PBSALES_US', engine, if_exists='append',index=False) #truncates the table\n",
    "\n",
    "conn = engine.raw_connection()\n",
    "cur = conn.cursor()\n",
    "output = io.StringIO()\n",
    "df.to_csv(output, sep='\\n', header=False, index=False)\n",
    "output.seek(0)\n",
    "contents = output.getvalue()\n",
    "cur.copy_from(output, 'PBSALES_US',null=\"\") # null values become ''\n",
    "conn.commit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "unexpected character after line continuation character (<ipython-input-37-3dd1fe298399>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-37-3dd1fe298399>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    \\COPY pbsales_us FROM 'C:\\Users\\meran\\Downloads\\PS.csv' DELIMITER ',' CSV HEADER;\u001b[0m\n\u001b[1;37m                                                                                     ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m unexpected character after line continuation character\n"
     ]
    }
   ],
   "source": [
    "\\COPY pbsales_us FROM 'C:\\Users\\meran\\Downloads\\PS.csv' DELIMITER ',' CSV HEADER;\n",
    "\n",
    "\n",
    "\\copy pbsales_us FROM 'temp_table.csv' WITH HEADER"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "fo = open(\"C:\\\\Users\\\\meran\\\\Downloads\\\\PS.csv\", \"wb\")\n",
    "#print \"Name of the file: \", fo.name\n",
    "\n",
    "# Close opend file\n",
    "fo.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "from datetime import datetime\n",
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "#df = pd.read_excel('C:\\\\Users\\\\meran\\\\Downloads\\\\PSALES.xls')\n",
    "data_xls = pd.read_csv('C:\\\\Users\\\\meran\\\\Downloads\\\\PSALES.xls',encoding ='latin1',sep='\\t', lineterminator='\\n')\n",
    "data_xls.columns = [c.lower().replace('%','per') for c in data_xls.columns]\n",
    "data_xls['load_date_time'] = datetime.now().strftime(\"%d/%m/%Y %H:%M:%S\") \n",
    "#data_xls.columns\n",
    "#data_xls\n",
    "\n",
    "engine = create_engine('postgresql://postgres:ranjeet@localhost:5432/postgres')\n",
    "data_xls.to_sql('psales', engine, if_exists='append',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting beautifulsoup4\n",
      "  Downloading beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)\n",
      "Collecting soupsieve>=1.2\n",
      "  Downloading soupsieve-2.0-py2.py3-none-any.whl (32 kB)\n",
      "Installing collected packages: soupsieve, beautifulsoup4\n",
      "Successfully installed beautifulsoup4-4.8.2 soupsieve-2.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install beautifulsoup4 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ptd_avg_discount\n"
     ]
    }
   ],
   "source": [
    "a='ptd_avg_discount'\n",
    "print(a.replace('%','per'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'address' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-17-b806367f7b7c>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mdf\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'Address'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0maddress\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'address' is not defined"
     ]
    }
   ],
   "source": [
    "from datetime import datetime\n",
    "df['load_date_time'] = now.strftime(\"%d/%m/%Y %H:%M:%S\") "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('test.txt','w+') as f: s=f.read()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('test.txt','w+') as f:\n",
    "    f.write('ranjeet kumar ji')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-38-6710e3491f5c>, line 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-38-6710e3491f5c>\"\u001b[1;36m, line \u001b[1;32m2\u001b[0m\n\u001b[1;33m    if os.path.getsize('test.txt')>0 and ()\u001b[0m\n\u001b[1;37m                                           ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "if os.path.getsize('test.txt')>0 and ()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def file_load_db(destination,dbuser,dbpassword,dbserver,database,processed):\n",
    "    f_comp='file_download_completed.txt'\n",
    "    if os.path.getsize(os.path.join(destination,f_comp))>0:\n",
    "        logger.debug('File is about to get loaded in postgres table')\n",
    "        try:\n",
    "            files_xls = [i for i in os.listdir(destination) if i.endswith('.xls')]\n",
    "            file_xls_path=os.path.join(destination,files_xls)\n",
    "            data_xls = pd.read_csv(file_xls_path,encoding ='latin1',sep='\\t', lineterminator='\\n')\n",
    "            data_xls.columns = [c.lower().replace('%','per') for c in data_xls.columns]\n",
    "            data_xls['load_date_time'] = datetime.now().strftime(\"%d/%m/%Y %H:%M:%S\")\n",
    "        except Exception as e:\n",
    "            logger.exception('Seems multiple file in incoming folder')\n",
    "            email_notification(FromEmail,ToEmail,EmailPassword,'Multiple File Issue','Multiple file issue')\n",
    "        try:\n",
    "            conn='postgresql://'+dbuser+':'+dbpassword+'@'+dbserver+'/'+database\n",
    "            #engine = create_engine('postgresql://postgres:ranjeet@localhost:5432/postgres')\n",
    "            engine = create_engine(conn)\n",
    "            data_xls.to_sql('psales', engine, if_exists='append',index=False)\n",
    "            logger.exception('Data Load Success')\n",
    "            \n",
    "        except Exception as e:\n",
    "            logger.exception('Data Load failed')\n",
    "            email_notification(FromEmail,ToEmail,EmailPassword,'Data Load failed','Data Load failed')\n",
    "        try:\n",
    "            logger.exception('Archiving .xls and file_download_completed.txt files')\n",
    "            src=os.path.join(destination,files_xls)\n",
    "            dest_fname=files_xls[:-4]+datetime.now().strftime('%Y_%m_%d_%H_%M_%S')+'.xls'\n",
    "            dest=os.path.join(processed,dest_fname)\n",
    "            shutil.move(src, dest)\n",
    "            logger.exception('.xls file archived in PROCESSED folder')\n",
    "            os.remove(os.path.join(destination,f_comp))\n",
    "        except Exception as e:\n",
    "            logger.exception('File Archibe failed')\n",
    "            email_notification(FromEmail,ToEmail,EmailPassword,'File Archibe failed','File Archibe failed')\n",
    "            \n",
    "\n",
    "\n",
    "\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'C:\\\\Users\\\\meran\\\\RK\\\\12020_03_04_17_12_19.txt'"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os  \n",
    "from datetime import datetime\n",
    "  \n",
    "# importing shutil module  \n",
    "import shutil \n",
    "fname='1.txt'\n",
    "path='C:\\\\Users\\\\meran'\n",
    "dpath='C:\\\\Users\\\\meran\\\\RK'\n",
    "dfname='1'+datetime.now().strftime('%Y_%m_%d_%H_%M_%S')+'.txt'\n",
    "\n",
    "shutil.move(os.path.join(path,fname), os.path.join(dpath,dfname))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'xyz'"
      ]
     },
     "execution_count": 54,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "files_xls='xyz.xls'\n",
    "files_xls[:-4]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
